import test from 'node:test';
import assert from 'node:assert/strict';
import {requiredBrowserChecks,validateBrowserResults,verifiedReport,repairPrototypeLayouts} from '../lib/verification.ts';
const report={business:{category:'Hotel'},prototypes:[{id:'request',kind:'request',qa:[{title:'Structural',passed:true}]},{id:'bilingual',kind:'bilingual',qa:[{title:'Structural',passed:true}]}]};
const results=()=>report.prototypes.map(p=>({prototypeId:p.id,checks:requiredBrowserChecks(report,p).map(key=>({key,passed:true}))}));
test('the expected browser checks depend on the prototype and company category',()=>{assert.ok(requiredBrowserChecks(report,report.prototypes[0]).includes('stay-dates'));assert.ok(requiredBrowserChecks(report,report.prototypes[1]).includes('english'));assert.ok(!requiredBrowserChecks({...report,business:{category:'Artigiani'}},report.prototypes[0]).includes('stay-dates'));});
test('complete browser results are normalized and permit readiness only after every check',()=>{const verified=validateBrowserResults(results(),report);assert.equal(verified.size,2);const complete={...report,prototypes:report.prototypes.map(p=>({...p,browser:verified.get(p.id)}))};assert.equal(verifiedReport(complete),true);complete.prototypes[0].browser.checks[0].passed=false;assert.equal(verifiedReport(complete),false);});
test('missing, duplicate, fabricated or non-boolean check results cannot complete a mission',()=>{const mutations=[r=>r.pop(),r=>r[0].checks.pop(),r=>r[0].checks[0].key='fake',r=>r[0].checks[0].passed='true',r=>r[0].checks[1]=r[0].checks[0],r=>r[1].prototypeId=r[0].prototypeId];for(const change of mutations){const value=results();change(value);assert.equal(validateBrowserResults(value,report),null);}assert.equal(validateBrowserResults(null,report),null);});
test('structural checks alone never imply a real browser verification',()=>{assert.equal(verifiedReport(report),false);const verification=validateBrowserResults(results(),report);const bad={...report,prototypes:report.prototypes.map(p=>({...p,qa:[{title:'Structural',passed:false}],browser:verification.get(p.id)}))};assert.equal(verifiedReport(bad),false);});

test('only layout failures receive one persisted repair with a new verification revision',()=>{const checks=validateBrowserResults(results(),report).get('request');checks.checks.find(q=>q.key==='mobile-layout').passed=false;const input={...report,verificationRevision:'before',prototypes:[{...report.prototypes[0],html:'<head></head><body>Fixture</body>',browser:checks}]};const repaired=repairPrototypeLayouts(input);assert.equal(repaired.repairAttempts,1);assert.notEqual(repaired.verificationRevision,'before');assert.match(repaired.prototypes[0].html,/data-bari-layout-repair/);assert.equal(repairPrototypeLayouts(repaired),repaired);});
test('functional failures are preserved for review instead of relabeled as a layout fix',()=>{const checks=validateBrowserResults(results(),report).get('request');checks.checks.find(q=>q.key==='local-submit').passed=false;const input={...report,prototypes:[{...report.prototypes[0],html:'<head></head>',browser:checks}]};assert.equal(repairPrototypeLayouts(input),input);});
