'use client';
import {useEffect,useRef} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {Sky} from 'three/addons/objects/Sky.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {createArchitecture,roadNetwork,coastlineLand,joinedNormals,world,type Footprint,type GeoPoint} from '@/lib/city-architecture';
import {createCityLife,createAgent,createWalkingRoutes,moveAlongRoute,type CityRoad} from '@/lib/city-life';
import {createWalkableArea,moveOnGround} from '@/lib/city-navigation';
import type {Business} from '@/lib/audit';
export type CityView='three'|'map'|'street';
export type SceneStatus='loading'|'ready'|'geometry-error'|'webgl-error';
export type TimeOfDay='day'|'sunset'|'night';
export type CityControls={focus:(lat:number,lon:number,close?:boolean)=>void;home:()=>void;zoom:(amount:number)=>void;promenade:()=>void;street:()=>void;team:()=>void;map:()=>void;north:()=>void};
export {world};
type Props={businesses:Business[];selected:Business|null;category:string;paused:boolean;stage:number;timeOfDay:TimeOfDay;onSelect:(b:Business)=>void;onReady:(c:CityControls)=>void;onViewChange:(view:CityView)=>void;onStatus:(status:SceneStatus)=>void};
const pinColors:Record<string,number>={'Hotel':0xd2a769,'B&B e case vacanza':0xc4a67a,'Ristoranti':0xc47662,'Bar e caffè':0xc99463,'Negozi':0x458e91,'Servizi':0x687f98,'Artigiani':0xa58e54,'Sport e benessere':0x729566};
const fallbackCoast:GeoPoint[]=[[16.7,41.218],[16.78,41.172],[16.816,41.153],[16.85,41.138],[16.863,41.133],[16.87,41.138],[16.878,41.137],[16.879,41.129],[16.901,41.115],[17.02,41.085]].map(([lon,lat])=>({lat,lon}));

export default function CityScene(props:Props){const host=useRef<HTMLDivElement>(null),latest=useRef(props);useEffect(()=>{latest.current=props;});
useEffect(()=>{
 const container=host.current!;let disposed=false,contextLost=false;const loadController=new AbortController();latest.current.onStatus('loading');container.dataset.buildings='0';container.dataset.localStreets='0';let renderRequested=true;const mobile=container.clientWidth<700;let renderer:THREE.WebGLRenderer;
 try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch{latest.current.onStatus('webgl-error');return;}
 renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.2:1.4));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.86;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.shadowMap.autoUpdate=false;container.appendChild(renderer.domElement);
 const scene=new THREE.Scene();scene.background=new THREE.Color(0xc5d8df);scene.fog=new THREE.FogExp2(0xb6cbd6,.00068);
 const initialTarget=world(41.1281,16.872),homeOffset=new THREE.Vector3(12,9,15);const camera=new THREE.PerspectiveCamera(39,1,.08,1800);camera.position.copy(initialTarget).add(homeOffset);
 const controls=new OrbitControls(camera,renderer.domElement);controls.target.copy(initialTarget);controls.enableDamping=true;controls.dampingFactor=.075;controls.maxPolarAngle=Math.PI/2-.12;controls.minDistance=1.5;controls.maxDistance=600;controls.screenSpacePanning=false;controls.zoomSpeed=.8;controls.panSpeed=.8;controls.mouseButtons={LEFT:THREE.MOUSE.PAN,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.ROTATE};controls.touches={ONE:THREE.TOUCH.PAN,TWO:THREE.TOUCH.DOLLY_ROTATE};
 const sky=new Sky();sky.scale.setScalar(1000);sky.material.uniforms.turbidity.value=3;sky.material.uniforms.rayleigh.value=1.6;sky.material.uniforms.mieCoefficient.value=.003;sky.material.uniforms.mieDirectionalG.value=.78;
 const sunDirection=new THREE.Vector3(-.62,.82,.32).normalize();sky.material.uniforms.sunPosition.value.copy(sunDirection.clone().multiplyScalar(1000));scene.add(sky);
 const pmrem=new THREE.PMREMGenerator(renderer),environmentScene=new RoomEnvironment();const environment=pmrem.fromScene(environmentScene,.025);environmentScene.dispose();scene.environment=environment.texture;scene.environmentIntensity=.35;pmrem.dispose();
 const ambient=new THREE.HemisphereLight(0xc4d9eb,0xb3a38a,.85);scene.add(ambient);const sun=new THREE.DirectionalLight(0xffedd3,2.5);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.bias=-.000015;sun.shadow.normalBias=.002;sun.shadow.radius=2;sun.shadow.camera.near=180;sun.shadow.camera.far=380;scene.add(sun,sun.target);
 const basic=(color:number,roughness=.86)=>new THREE.MeshStandardMaterial({color,roughness});
 const load=new THREE.TextureLoader();const stone=load.load('/textures/limestone.png',()=>{if(!disposed){renderRequested=true;renderer.shadowMap.needsUpdate=true;}});stone.colorSpace=THREE.SRGBColorSpace;stone.wrapS=stone.wrapT=THREE.RepeatWrapping;stone.repeat.set(3,3);stone.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());
 const plaster=load.load('/textures/plaster.png',()=>{if(!disposed)renderRequested=true;});plaster.colorSpace=THREE.SRGBColorSpace;plaster.wrapS=plaster.wrapT=THREE.RepeatWrapping;plaster.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());
 const groundMaterial=basic(0xcac8b8,.99);groundMaterial.userData.mapColor=0xe9edf0;let land=coastlineLand(fallbackCoast,groundMaterial);scene.add(land);
 const waterNormal=load.load('/textures/water-normal.jpg',()=>{if(!disposed)renderRequested=true;});waterNormal.wrapS=waterNormal.wrapT=THREE.RepeatWrapping;waterNormal.anisotropy=4;
 const oceanMaterial=new THREE.ShaderMaterial({uniforms:{normalMap:{value:waterNormal},time:{value:0},sunDirection:{value:sunDirection},brightness:{value:1},mapView:{value:0},sunTint:{value:new THREE.Color(0xffe9c0)}},vertexShader:`varying vec3 vWorld; void main(){vec4 w=modelMatrix*vec4(position,1.0);vWorld=w.xyz;gl_Position=projectionMatrix*viewMatrix*w;}`,fragmentShader:`uniform float time; uniform float brightness; uniform float mapView; uniform vec3 sunDirection; uniform vec3 sunTint; uniform sampler2D normalMap; varying vec3 vWorld;
 void main(){vec2 p=vWorld.xz;vec3 t1=texture2D(normalMap,p*.41+vec2(time*.009,time*.003)).rgb*2.0-1.0;vec3 t2=texture2D(normalMap,p*.71+vec2(-time*.006,time*.007)).rgb*2.0-1.0;vec3 n=normalize(vec3((t1.x+t2.x)*.1,1.0,(t1.y+t2.y)*.1));vec3 v=normalize(cameraPosition-vWorld);float fresnel=pow(1.0-max(dot(v,n),0.0),3.0);float sparkle=pow(max(dot(n,normalize(sunDirection+v)),0.0),160.0);vec3 base=vec3(.012,.175,.29)+vec3(.009,.018,.02)*(t1.z+t2.z);vec3 color=(mix(base,vec3(.16,.43,.51),fresnel*.45)+sunTint*sparkle*.75)*brightness;gl_FragColor=vec4(mix(color,vec3(.35,.65,.9),mapView),1.0);
 #include <tonemapping_fragment>
 #include <colorspace_fragment>
 }`});
 const ocean=new THREE.Mesh(new THREE.PlaneGeometry(5000,5000),oceanMaterial);ocean.rotation.x=-Math.PI/2;ocean.position.y=-.025;scene.add(ocean);
 const architectureRoot=new THREE.Group();scene.add(architectureRoot);let facadeGroup:THREE.Group|null=null;const facadeRoots:THREE.Group[]=[],facadeTiles:{group:THREE.Group;fallback:THREE.Group;x:number;z:number}[]=[];let roofCenters:{x:number;z:number;height:number}[]=[];
 const roofGrid=new Map<string,{x:number;z:number;height:number}[]>();const roofHeight=(p:THREE.Vector3)=>{const key=Math.floor(p.x/3)+','+Math.floor(p.z/3);const candidates=roofGrid.get(key)||[];let closest=1.4,result=.15;for(const c of candidates){const d=Math.hypot(c.x-p.x,c.z-p.z);if(d<closest){closest=d;result=c.height;}}return result;};
 const addBox=(w:number,h:number,d:number,p:THREE.Vector3,material:THREE.Material)=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material);mesh.position.copy(p).add(new THREE.Vector3(0,h/2,0));mesh.castShadow=true;mesh.receiveShadow=true;scene.add(mesh);return mesh;};
 const mapped=props.businesses.filter(b=>b.lat&&b.lon),markerGeometry=new THREE.CylinderGeometry(.034,.022,.12,6),markers=new THREE.InstancedMesh(markerGeometry,new THREE.MeshStandardMaterial({color:0xffffff,roughness:.32,metalness:.25,emissive:0x1f2425,emissiveIntensity:.06}),mapped.length);
 const markerMatrices:THREE.Matrix4[]=[],dummy=new THREE.Object3D();markers.instanceMatrix.setUsage(THREE.DynamicDrawUsage);scene.add(markers);markers.visible=false;
 function updateMarkers(){mapped.forEach((b,i)=>{const p=world(b.lat!,b.lon!);dummy.position.copy(p);dummy.position.y=roofHeight(p)+.09;dummy.scale.set(1,1,1);dummy.updateMatrix();markers.setMatrixAt(i,dummy.matrix);markerMatrices[i]=dummy.matrix.clone();markers.setColorAt(i,new THREE.Color(pinColors[b.category]||0x688a85));});markers.instanceMatrix.needsUpdate=true;if(markers.instanceColor)markers.instanceColor.needsUpdate=true;markers.computeBoundingSphere();}
 updateMarkers();
 // Landmark models are architectural approximations placed at their real coordinates.
 const stoneMat=new THREE.MeshStandardMaterial({color:0xe4dac1,map:stone,roughness:.84,bumpMap:stone,bumpScale:.002});
 const basilica=world(41.1306,16.8703),church=new THREE.Group();church.position.copy(basilica);church.rotation.y=.22;scene.add(church);
 const churchBox=(w:number,h:number,d:number,x:number,y:number,z:number)=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),stoneMat);mesh.position.set(x,h/2+y,z);mesh.castShadow=true;mesh.receiveShadow=true;church.add(mesh);};
 churchBox(1.65,.9,2.9,0,0,0);churchBox(.5,1.45,.5,-.62,0,-1.25);churchBox(.5,1.45,.5,.62,0,-1.25);churchBox(1.1,.16,3.03,0,.9,0);
 const rose=new THREE.Mesh(new THREE.TorusGeometry(.105,.026,8,24),basic(0xc5b697));rose.position.set(0,.73,-1.46);church.add(rose);
 const doorMat=basic(0x4b4540);for(const x of [-.42,0,.42]){const door=new THREE.Mesh(new THREE.BoxGeometry(.16,.3,.025),doorMat);door.position.set(x,.16,-1.46);church.add(door);}
 const castle=world(41.1285,16.8655),castleMat=basic(0xc6b99e);for(const z of [-.74,.74])addBox(2.25,.55,.32,castle.clone().add(new THREE.Vector3(0,0,z)),castleMat);for(const x of [-.96,.96])addBox(.32,.55,1.65,castle.clone().add(new THREE.Vector3(x,0,0)),castleMat);
 for(const x of [-.98,.98])for(const z of [-.78,.78]){const p=castle.clone().add(new THREE.Vector3(x,0,z));addBox(.5,.86,.5,p,castleMat);for(let i=0;i<3;i++){for(const side of [-1,1])addBox(.095,.095,.11,p.clone().add(new THREE.Vector3(-.17+i*.17,.86,side*.2)),castleMat);}}
 const gableShape=new THREE.Shape();gableShape.moveTo(-.83,0);gableShape.lineTo(0,.34);gableShape.lineTo(.83,0);gableShape.closePath();const churchRoof=new THREE.Mesh(new THREE.ExtrudeGeometry(gableShape,{depth:2.92,bevelEnabled:false}),basic(0xad8c76));churchRoof.position.set(0,1.04,-1.46);church.add(churchRoof);
 for(const x of [-.7,.7]){const column=new THREE.Mesh(new THREE.CylinderGeometry(.04,.045,.42,8),stoneMat);column.position.set(x,.28,-1.53);church.add(column);}churchBox(1.9,.04,.35,0,0,-1.5);
 const theatre=new THREE.Group();theatre.position.copy(world(41.12255,16.8722));theatre.rotation.y=.48;scene.add(theatre);const theatreFacade=basic(0xc78e7d),theatreTrim=basic(0xead7b6);
 const theatreBox=(w:number,h:number,d:number,x:number,y:number,z:number,mat:THREE.Material)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y+h/2,z);m.castShadow=true;m.receiveShadow=true;theatre.add(m);};
 theatreBox(1.4,.83,2.25,0,0,0,theatreFacade);theatreBox(1.56,.055,2.3,0,.82,0,theatreTrim);theatreBox(1.45,.045,2.3,0,.43,0,theatreTrim);
 for(const x of [-.57,-.28,0,.28,.57]){theatreBox(.07,.72,.065,x,.06,-1.15,theatreTrim);theatreBox(.13,.20,.024,x,.15,-1.17,doorMat);theatreBox(.12,.15,.024,x,.54,-1.17,doorMat);}const dome=new THREE.Mesh(new THREE.SphereGeometry(.68,20,10,0,Math.PI*2,0,Math.PI/2),basic(0x937762));dome.scale.set(1,.38,1.35);dome.position.set(0,.85,.32);theatre.add(dome);
 // Virtual command campus with glass facades; it is not a real Bari property.
 const hq=world(41.1278,16.8726),glassMat=new THREE.MeshPhysicalMaterial({color:0x3c606a,metalness:.25,roughness:.17,clearcoat:1,clearcoatRoughness:.12,envMapIntensity:1.25}),campusStone=basic(0xd4cec0),hqPad=basic(0xb8b8ac);
 addBox(1.45,.018,1.2,hq,hqPad);addBox(.65,.28,.52,hq,glassMat);addBox(.74,.027,.6,hq.clone().add(new THREE.Vector3(0,.28,0)),campusStone);
 for(const x of [-.25,0,.25])addBox(.012,.27,.53,hq.clone().add(new THREE.Vector3(x,.01,0)),campusStone);
 const labs=[hq.clone().add(new THREE.Vector3(-.6,0,.44)),hq.clone().add(new THREE.Vector3(-.18,0,.65)),hq.clone().add(new THREE.Vector3(.24,0,.65)),hq.clone().add(new THREE.Vector3(.64,0,.4))];
 labs.forEach(p=>{addBox(.12,.055,.1,p.clone().add(new THREE.Vector3(0,0,-.15)),campusStone);});
 function label(text:string,p:THREE.Vector3,accent=false){const c=document.createElement('canvas');c.width=512;c.height=100;const ctx=c.getContext('2d')!;const namedAgent=['NORA','LEO','ADA','LUCA'].includes(text);if(namedAgent)c.width=192;ctx.fillStyle=accent?'rgba(19,49,55,.9)':'rgba(247,247,242,.9)';ctx.beginPath();ctx.roundRect(6,15,c.width-12,68,14);ctx.fill();ctx.fillStyle=accent?'#eef2ed':'#4d6969';ctx.font=namedAgent?'700 38px system-ui':'600 29px system-ui';ctx.textAlign='center';ctx.fillText(text,c.width/2,59);const texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,depthTest:false,transparent:true}));sprite.position.copy(p);sprite.scale.set(15,2.93,1);sprite.userData.label=true;scene.add(sprite);return sprite;}
 const labels=[label('BARI VECCHIA',world(41.132,16.87).add(new THREE.Vector3(0,2.6,0))),label('MURAT',world(41.122,16.869).add(new THREE.Vector3(0,2.8,0))),label('MADONNELLA',world(41.117,16.89).add(new THREE.Vector3(0,2.6,0))),label('PORTO DI BARI',world(41.143,16.857).add(new THREE.Vector3(0,1,0))),label('CENTRO DI COMANDO',hq.clone().add(new THREE.Vector3(0,.5,0)),true)];
 const agentColors=[0x21aa99,0xd9a34a,0x9784bb,0x78a082];const agentNames=['NORA','LEO','ADA','LUCA'];
 const agents=agentColors.map((color,i)=>{const group=createAgent(color);group.position.copy(labs[i]);scene.add(group);return group;});
 const agentLabels=agents.map((a,i)=>label(agentNames[i],a.position,true));agentLabels.forEach(s=>s.scale.set(1.6,.32,1));
 let cityLife:ReturnType<typeof createCityLife>|null=null;let walkingRoutes:ReturnType<typeof createWalkingRoutes>|null=null;let agentRoute:ReturnType<ReturnType<typeof createWalkingRoutes>>|null=null;const windowLights:THREE.MeshStandardMaterial[]=[];
 const ring=new THREE.Mesh(new THREE.RingGeometry(.25,.28,48),new THREE.MeshBasicMaterial({color:0x1dc8b2,side:THREE.DoubleSide,transparent:true,opacity:.92}));ring.rotation.x=-Math.PI/2;ring.visible=false;scene.add(ring);
 const beacon=new THREE.Mesh(new THREE.CylinderGeometry(.008,.008,1.5,6),new THREE.MeshBasicMaterial({color:0x28af9f,transparent:true,opacity:.35}));beacon.visible=false;scene.add(beacon);
 const routeMaterial=new THREE.LineDashedMaterial({color:0x2ba58f,dashSize:.23,gapSize:.12,transparent:true,opacity:.8});let route:THREE.Line|null=null,lastId='',lastCategory='',lastStage=-1,stageTime=0,elapsed=0,frame=0,architectureReady=false;
 let destination:THREE.Vector3|null=null,destinationDistance:number|null=null,destinationPose:{position:THREE.Vector3;target:THREE.Vector3}|null=null;let streetView=false,mapView=false;let walkable:(p:THREE.Vector3)=>boolean=()=>false;const homeDistance=camera.position.distanceTo(controls.target);
 const promenadeTarget=world(41.1281,16.872);let streetPosition=world(41.1231825,16.8776836).setY(.089),streetDirection=new THREE.Vector3(-.7,0,-.7).normalize();
 const cancelFlight=()=>{destination=null;destinationDistance=null;destinationPose=null;renderRequested=true;};controls.addEventListener('start',cancelFlight);
 const setPose=(position:THREE.Vector3,target:THREE.Vector3,isStreet=false)=>{renderRequested=true;destination=null;destinationDistance=null;destinationPose={position,target};streetView=isStreet;mapView=false;latest.current.onViewChange(isStreet?'street':'three');};
 latest.current.onReady({focus:(lat,lon,close=false)=>{if(close){const p=world(lat,lon);setPose(p.clone().add(new THREE.Vector3(7,6,8)),p);}else{destinationPose=null;streetView=false;mapView=false;latest.current.onViewChange('three');destination=world(lat,lon);destinationDistance=homeDistance;}},home:()=>{setPose(initialTarget.clone().add(homeOffset),initialTarget.clone());},promenade:()=>{setPose(promenadeTarget.clone().add(homeOffset),promenadeTarget.clone());},street:()=>{if(!architectureReady)return;setPose(streetPosition.clone(),streetPosition.clone().addScaledVector(streetDirection,3).setY(.081),true);},team:()=>{setPose(hq.clone().add(new THREE.Vector3(.9,.65,1.25)),hq.clone().add(new THREE.Vector3(0,.02,.25)));},map:()=>{const target=controls.target.clone().setY(0),distance=Math.max(18,camera.position.distanceTo(controls.target));setPose(target.clone().add(new THREE.Vector3(0,distance,.001)),target);mapView=true;latest.current.onViewChange('map');},north:()=>{if(streetView){cancelFlight();controls.target.copy(camera.position).add(new THREE.Vector3(0,0,-3));return;}const wasMap=mapView;const target=controls.target.clone(),offset=camera.position.clone().sub(target);setPose(target.clone().add(new THREE.Vector3(0,offset.y,Math.max(.001,Math.hypot(offset.x,offset.z)))),target,streetView);if(wasMap){mapView=true;latest.current.onViewChange('map');}},zoom:amount=>{cancelFlight();if(streetView){streetView=false;mapView=false;latest.current.onViewChange('three');controls.target.y=0;camera.position.y=Math.max(2,camera.position.y);}const offset=camera.position.clone().sub(controls.target).multiplyScalar(amount);offset.setLength(THREE.MathUtils.clamp(offset.length(),1.5,600));camera.position.copy(controls.target.clone().add(offset));destinationDistance=null;}});
 const keys=new Set<string>();const keydown=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.closest('input,textarea,select,[contenteditable=true]')||document.querySelector('[role=dialog]')||e.ctrlKey||e.metaKey||e.altKey)return;if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(e.key.toLowerCase())){keys.add(e.key.toLowerCase());if(streetView)e.preventDefault();}};const keyup=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase());const clearKeys=()=>keys.clear();window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);window.addEventListener('blur',clearKeys);

 const shadowTarget=new THREE.Vector3(9999,0,0);let shadowRadius=0;const updateShadows=()=>{const radius=Math.max(7,Math.min(80,camera.position.distanceTo(controls.target)*.66));if(shadowTarget.distanceTo(controls.target)<.45&&Math.abs(radius-shadowRadius)<2)return;shadowTarget.copy(controls.target);shadowRadius=radius;sun.target.position.copy(controls.target);sun.position.copy(controls.target).addScaledVector(sunDirection,280);sun.shadow.camera.left=-radius;sun.shadow.camera.right=radius;sun.shadow.camera.top=radius;sun.shadow.camera.bottom=-radius;sun.shadow.camera.updateProjectionMatrix();renderer.shadowMap.needsUpdate=true;};
 const mapHud=container.closest('.world') as HTMLElement;const scaleLabel=mapHud?.querySelector('[data-map-scale]') as HTMLElement|null;
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),groundPlane=new THREE.Plane(new THREE.Vector3(0,1,0),0);let pointerX=0,pointerY=0,dragX=0,dragY=0,dragPointer:number|null=null;const pointers=new Set<number>();let gestureMoved=false;
 const lostContext=(e:Event)=>{e.preventDefault();contextLost=true;loadController.abort();latest.current.onStatus('webgl-error');};renderer.domElement.addEventListener('webglcontextlost',lostContext);
 const down=(e:PointerEvent)=>{pointers.add(e.pointerId);if(pointers.size>1)gestureMoved=true;else{pointerX=dragX=e.clientX;pointerY=dragY=e.clientY;gestureMoved=false;}dragPointer=e.pointerId;if(streetView&&!destinationPose){cancelFlight();renderer.domElement.setPointerCapture(e.pointerId);}else if(!streetView)cancelFlight();};
 const move=(e:PointerEvent)=>{if(Math.hypot(e.clientX-pointerX,e.clientY-pointerY)>5)gestureMoved=true;if(!streetView||destinationPose||dragPointer!==e.pointerId||pointers.size!==1)return;const direction=controls.target.clone().sub(camera.position).normalize(),yaw=Math.atan2(direction.x,direction.z)-(e.clientX-dragX)*.006,pitch=THREE.MathUtils.clamp(Math.asin(direction.y)-(e.clientY-dragY)*.004,-.35,.35);controls.target.copy(camera.position).add(new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch)).multiplyScalar(3));dragX=e.clientX;dragY=e.clientY;renderRequested=true;};
 const cancelPointer=(e:PointerEvent)=>{pointers.delete(e.pointerId);dragPointer=null;gestureMoved=true;};const up=(e:PointerEvent)=>{pointers.delete(e.pointerId);dragPointer=null;if(gestureMoved||Math.hypot(e.clientX-pointerX,e.clientY-pointerY)>5||e.button!==0)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);const hit=mapView?ray.intersectObject(markers)[0]:undefined;const obstruction=ray.intersectObjects([architectureRoot,church,theatre],true)[0];if(hit?.instanceId!==undefined&&(!obstruction||obstruction.distance+.015>=hit.distance)){const b=mapped[hit.instanceId];if(latest.current.category==='Tutte'||b.category===latest.current.category)latest.current.onSelect(b);return;}const point=new THREE.Vector3();if(obstruction&&!mapView)point.copy(obstruction.point).setY(0);else if(!ray.ray.intersectPlane(groundPlane,point))return;let nearest:Business|null=null,distance=.65;for(const b of mapped){if(latest.current.category!=='Tutte'&&b.category!==latest.current.category)continue;const d=world(b.lat!,b.lon!).distanceTo(point);if(d<distance){distance=d;nearest=b;}}if(nearest)latest.current.onSelect(nearest);};const contextMenu=(e:Event)=>e.preventDefault();renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointercancel',cancelPointer);renderer.domElement.addEventListener('contextmenu',contextMenu);
 const resize=()=>{renderRequested=true;const r=container.getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(container);resize();
 function addStreetLife(roads:{kind?:string;geometry?:GeoPoint[]}[]){const trees:THREE.Vector3[]=[],cars:{p:THREE.Vector3;angle:number}[]=[];for(let i=0;i<roads.length;i++){const road=roads[i],g=road.geometry;if(!g||g.length<2)continue;const p=world(g[0].lat,g[0].lon),q=world(g[1].lat,g[1].lon),dir=q.clone().sub(p);if(dir.length()<.2)continue;dir.normalize();const lateral=new THREE.Vector3(-dir.z,0,dir.x);if(i%3===0&&road.kind!=='pedestrian'&&p.distanceTo(initialTarget)<150)trees.push(p.clone().addScaledVector(lateral,.16));if(i%2===0&&!['pedestrian','footway','path','steps'].includes(road.kind||'')&&p.distanceTo(initialTarget)<110)cars.push({p:p.clone().addScaledVector(dir,.12).addScaledVector(lateral,.045),angle:Math.atan2(dir.x,dir.z)});}
  const leaf=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1,2),basic(0x4e6749),trees.length*3),trunks=new THREE.InstancedMesh(new THREE.CylinderGeometry(.011,.015,.17,5),basic(0x726453),trees.length);trees.forEach((p,i)=>{dummy.position.copy(p).setY(.09);dummy.scale.set(1,1,1);dummy.updateMatrix();trunks.setMatrixAt(i,dummy.matrix);for(let l=0;l<3;l++){dummy.position.copy(p).add(new THREE.Vector3(Math.sin(i+l)*.035,.21+l*.025,Math.cos(i+l)*.035));dummy.scale.set(.08,.085,.07);dummy.rotation.set(i,l*.3,0);dummy.updateMatrix();leaf.setMatrixAt(i*3+l,dummy.matrix);}});dummy.rotation.set(0,0,0);leaf.castShadow=true;trunks.castShadow=true;scene.add(leaf,trunks);
  const bodies=new THREE.InstancedMesh(new THREE.BoxGeometry(.065,.043,.145),new THREE.MeshStandardMaterial({color:0xffffff,roughness:.4,metalness:.3}),cars.length),carGlass=new THREE.InstancedMesh(new THREE.BoxGeometry(.055,.026,.075),glassMat,cars.length);const carColors=[0xdbd8d0,0x4a535a,0x9a5c4d,0x6b818a,0xe9e7e0,0x3a4652];cars.forEach((c,i)=>{dummy.position.copy(c.p).setY(.055);dummy.rotation.set(0,c.angle,0);dummy.scale.set(1,1,1);dummy.updateMatrix();bodies.setMatrixAt(i,dummy.matrix);bodies.setColorAt(i,new THREE.Color(carColors[i%carColors.length]));dummy.position.y=.084;dummy.updateMatrix();carGlass.setMatrixAt(i,dummy.matrix);});dummy.rotation.set(0,0,0);bodies.castShadow=true;carGlass.castShadow=true;scene.add(bodies,carGlass);
 }
 const harbour=world(41.1372,16.862),hullMaterial=basic(0xf0eeeb),deckMaterial=basic(0x697b82);for(let i=0;i<4;i++){const p=harbour.clone().add(new THREE.Vector3(-7+i*6,-.018,-10+(i%2)*6));const hull=new THREE.Mesh(new THREE.CapsuleGeometry(.38,1.7,3,8),hullMaterial);hull.rotation.z=Math.PI/2;hull.rotation.y=.7;hull.scale.z=.75;hull.position.copy(p).setY(.22);hull.castShadow=true;scene.add(hull);addBox(1.1,.33,.42,p.clone().add(new THREE.Vector3(0,.35,0)),hullMaterial);addBox(.9,.1,.38,p.clone().add(new THREE.Vector3(0,.68,0)),deckMaterial);}
 const fetchJson=(path:string)=>fetch(path,{signal:loadController.signal}).then(r=>{if(!r.ok)throw Error(path);return r.json();});
 Promise.all([fetchJson('/data/buildings.json'),fetchJson('/data/geography.json'),fetchJson('/data/shoreline.json'),fetchJson('/data/local-streets.json')]).then(async ([rawBuildings,rawGeo,rawShore,local])=>{
  if(disposed)return;const data=rawBuildings as {buildings:Footprint[]},geography=rawGeo as {roads:CityRoad[]},shore=rawShore as {points:GeoPoint[]};
  const localRoads=((local as {roads:(CityRoad&{tags?:Record<string,string>})[]}).roads).filter(r=>!['yes','building_passage'].includes(r.tags?.tunnel||'')&&r.tags?.indoor!=='yes'&&r.tags?.covered!=='yes'&&r.tags?.area!=='yes'&&r.tags?.footway!=='crossing');const roads=[...geography.roads,...localRoads];
  const coastVectors=shore.points.map(p=>world(p.lat,p.lon)),coastNormals=joinedNormals(coastVectors),streetAnchor=world(41.12346,16.87713);let streetIndex=1,nearestSegment=Infinity;
  for(let i=1;i<coastVectors.length;i++){const midpoint=coastVectors[i-1].clone().add(coastVectors[i]).multiplyScalar(.5),distance=midpoint.distanceToSquared(streetAnchor);if(distance<nearestSegment){nearestSegment=distance;streetIndex=i;}}
  const inland=coastNormals[streetIndex-1].clone().add(coastNormals[streetIndex]).normalize();streetPosition=coastVectors[streetIndex-1].clone().add(coastVectors[streetIndex]).multiplyScalar(.5).addScaledVector(inland,.08).setY(.089);streetDirection=coastVectors[streetIndex-1].clone().sub(coastVectors[streetIndex]).normalize();

  scene.remove(land);land.geometry.dispose();land=coastlineLand(shore.points,groundMaterial);scene.add(land);const landmarks=[{p:basilica,r:1.6},{p:castle,r:1.45},{p:world(41.12255,16.8722),r:1.4}];const architecturalRecords=data.buildings.filter(b=>{const p=b.geometry.reduce((a,q)=>a.add(world(q.lat,q.lon)),new THREE.Vector3()).multiplyScalar(1/b.geometry.length);return !landmarks.some(l=>p.distanceTo(l.p)<l.r);});const built=await createArchitecture(architecturalRecords,stone,loadController.signal,plaster);architectureRoot.add(built.group);
  const approximate:Footprint[]=[],seen=new Set<string>();for(const b of mapped){if(b.lat!>=41.105&&b.lat!<=41.142&&b.lon!>=16.837&&b.lon!<=16.902)continue;const key=b.lat!.toFixed(4)+','+b.lon!.toFixed(4);if(seen.has(key))continue;seen.add(key);const lat=b.lat!,lon=b.lon!;approximate.push({id:'visual-'+b.id,tags:{building:'yes'},geometry:[{lat:lat-.000045,lon:lon-.000065},{lat:lat-.000045,lon:lon+.000065},{lat:lat+.000045,lon:lon+.000065},{lat:lat+.000045,lon:lon-.000065}]});}
  const outerCity=await createArchitecture(approximate,stone,loadController.signal,plaster);architectureRoot.add(outerCity.group);facadeGroup=built.group.userData.facades as THREE.Group;facadeRoots.push(facadeGroup,outerCity.group.userData.facades);facadeTiles.push(...built.group.userData.facadeTiles,...outerCity.group.userData.facadeTiles);windowLights.push(built.group.userData.windowLight,outerCity.group.userData.windowLight);roofCenters=[...built.centers,...outerCity.centers];
  for(const c of roofCenters){const x=Math.floor(c.x/3),z=Math.floor(c.z/3);for(let i=-1;i<=1;i++)for(let j=-1;j<=1;j++){const key=(x+i)+','+(z+j);if(!roofGrid.has(key))roofGrid.set(key,[]);roofGrid.get(key)!.push(c);}}
  scene.add(roadNetwork(roads,stone));lightingMode='';addStreetLife(geography.roads);cityLife=createCityLife(roads,shore.points);walkingRoutes=createWalkingRoutes(roads);const groundWalkable=createWalkableArea(data.buildings.concat(approximate),shore.points);walkable=p=>groundWalkable(p)&&cityLife!.clearOfFurniture(p);scene.add(cityLife.group);updateMarkers();architectureReady=true;lastId='';lastCategory='';renderer.shadowMap.needsUpdate=true;
  container.dataset.geometry='ready';if(!contextLost)latest.current.onStatus('ready');renderRequested=true;container.dataset.buildings=String(built.group.userData.footprints);container.dataset.windows=String(built.group.userData.windows);container.dataset.localStreets=String(localRoads.length);container.dataset.people=String(cityLife.people);container.dataset.traffic=String(cityLife.cars);
 }).catch(error=>{if(!disposed&&!contextLost){container.dataset.geometry='unavailable';latest.current.onStatus('geometry-error');console.error('Bari geometry could not be loaded',error);}});
 let lightingMode='';let nightAmount=0;let lastDetailKey='';
 function updateLighting(){const mode=latest.current.timeOfDay,key=mode+'|'+mapView+'|'+streetView;if(key===lightingMode)return;renderRequested=true;lightingMode=key;scene.traverse(o=>{if(o instanceof THREE.Mesh){if(o.userData.hideOnMap)o.visible=!mapView;const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats){if(!(m instanceof THREE.MeshStandardMaterial)||m.userData.mapColor===undefined)continue;if(m.userData.originalColor===undefined){m.userData.originalColor=m.color.getHex();m.userData.originalMap=m.map;}m.color.setHex(mapView?m.userData.mapColor:m.userData.originalColor);const texture=mapView?null:m.userData.originalMap;if(m.map!==texture){m.map=texture;m.needsUpdate=true;}}}});nightAmount=mode==='night'?1:mode==='sunset'?.2:0;
  const day=mode==='day',night=mode==='night';sunDirection.set(day?-.62:night?.45:-.92,day?.82:night?.32:.16,day?.32:night?-.5:.3).normalize();sky.material.uniforms.sunPosition.value.copy(sunDirection.clone().multiplyScalar(1000));sky.visible=!night&&!mapView;markers.visible=mapView;beacon.visible=mapView&&!!(latest.current.selected?.lat&&latest.current.selected?.lon);camera.near=streetView?.02:.08;camera.updateProjectionMatrix();controls.enabled=!streetView;controls.maxPolarAngle=mapView?.01:Math.PI/2-.12;
  scene.background=new THREE.Color(night?0x122333:day?0xc5d8df:0xe8bc93);scene.fog=new THREE.Fog(night?0x142b3d:day?0xcce3eb:0xd5b696,40,190);sun.color.set(night?0x9dbbd8:day?0xfff5de:0xffae71);sun.intensity=night?.5:day?3.1:2.1;ambient.color.set(night?0x6581ac:day?0xc4d9eb:0xe5b9a2);ambient.intensity=night?.35:day?.35:.45;scene.environmentIntensity=night?.16:.3;
  oceanMaterial.uniforms.mapView.value=mapView?1:0;renderer.shadowMap.enabled=!mapView;groundMaterial.color.setHex(mapView?0xe9edf0:0xcac8b8);
  oceanMaterial.uniforms.brightness.value=night?.18:day?1:.75;oceanMaterial.uniforms.sunTint.value.set(night?0xaecaff:day?0xffe9c0:0xff9e65);renderer.toneMappingExposure=night?1.1:day?.87:.95;windowLights.forEach(m=>{m.emissiveIntensity=nightAmount*2;});shadowTarget.set(9999,0,0);renderer.shadowMap.needsUpdate=true;container.dataset.timeOfDay=mode;container.dataset.mapView=String(mapView);if(mapView){scene.fog=null;ambient.intensity=1.4;sun.intensity=1.5;renderer.toneMappingExposure=1.1;}
 }

 let lastRenderKey='',lastTick=0,lastShadowTime=0;let previousTime=performance.now();const render=(now:number)=>{
  frame=requestAnimationFrame(render);if(contextLost||!architectureReady||now-lastTick<32)return;lastTick=now;const rawDt=(now-previousTime)/1000,dt=Math.min(rawDt,.08),cameraBlend=1-Math.exp(-Math.min(rawDt,.5)*6);previousTime=now;
  if(!latest.current.paused){elapsed+=dt;stageTime+=dt;}if(latest.current.stage!==lastStage){lastStage=latest.current.stage;stageTime=0;agentRoute=null;}
  const selected=latest.current.selected;
  if((selected?.id||'')!==lastId){lastId=selected?.id||'';agentRoute=null;if(route){scene.remove(route);route.geometry.dispose();route=null;}ring.visible=!!(selected?.lat&&selected?.lon);beacon.visible=mapView&&ring.visible;if(selected?.lat&&selected?.lon){const p=world(selected.lat,selected.lon),roofRay=new THREE.Raycaster(p.clone().setY(15),new THREE.Vector3(0,-1,0)),roofHit=roofRay.intersectObjects([architectureRoot,church,theatre],true)[0],height=roofHit?.point.y??.018;ring.position.copy(p).setY(height+.015);beacon.position.copy(p).setY(height+.8);if(walkingRoutes){const path=walkingRoutes(hq,p);const points=(path.reachable?path.points:[]).map(p=>p.clone().setY(.04));route=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),routeMaterial);route.computeLineDistances();scene.add(route);}}}
  if(latest.current.category!==lastCategory){lastCategory=latest.current.category;mapped.forEach((b,i)=>{const matrix=markerMatrices[i].clone();if(lastCategory!=='Tutte'&&b.category!==lastCategory)matrix.scale(new THREE.Vector3(0,0,0));markers.setMatrixAt(i,matrix);});markers.instanceMatrix.needsUpdate=true;}
  if(destinationPose){renderRequested=true;camera.position.lerp(destinationPose.position,cameraBlend);controls.target.lerp(destinationPose.target,cameraBlend);if(camera.position.distanceTo(destinationPose.position)<.005){camera.position.copy(destinationPose.position);controls.target.copy(destinationPose.target);destinationPose=null;}}
  if(destination){renderRequested=true;const delta=destination.clone().sub(controls.target).multiplyScalar(cameraBlend);controls.target.add(delta);camera.position.add(delta);if(delta.length()<.004)destination=null;}
  if(destinationDistance!==null){renderRequested=true;const offset=camera.position.clone().sub(controls.target),distance=offset.length();offset.setLength(THREE.MathUtils.lerp(distance,destinationDistance,cameraBlend));camera.position.copy(controls.target.clone().add(offset));if(Math.abs(distance-destinationDistance)<.05)destinationDistance=null;}
  if(streetView&&!destinationPose&&keys.size){const direction=controls.target.clone().sub(camera.position).setY(0).normalize(),side=new THREE.Vector3(direction.z,0,-direction.x),movement=new THREE.Vector3();if(keys.has('w')||keys.has('arrowup'))movement.add(direction);if(keys.has('s')||keys.has('arrowdown'))movement.sub(direction);if(keys.has('a')||keys.has('arrowleft'))movement.add(side);if(keys.has('d')||keys.has('arrowright'))movement.sub(side);movement.normalize().multiplyScalar(dt*.15);const next=moveOnGround(camera.position,movement,walkable),delta=next.sub(camera.position);camera.position.add(delta);controls.target.add(delta);renderRequested=true;}
  const distance=camera.position.distanceTo(controls.target);
  agents.forEach((a,i)=>{const active=lastStage===i;let walking=false;
   if(active){let from=i===0?hq:labs[i-1],to=labs[i];if(i===0&&selected?.lat&&selected?.lon)to=walkingRoutes?.nearest(world(selected.lat,selected.lon))||world(selected.lat,selected.lon);if(i===1&&selected?.lat&&selected?.lon)from=walkingRoutes?.nearest(world(selected.lat,selected.lon))||world(selected.lat,selected.lon);if(!agentRoute&&walkingRoutes)agentRoute=walkingRoutes(from,to);if(agentRoute){const progress=agentRoute.length?Math.min(stageTime*.055/agentRoute.length,1):1;walking=progress<1;a.rotation.y=moveAlongRoute(agentRoute,progress,a.position);}else{const travel=from.distanceTo(to),progress=travel?Math.min(stageTime*.055/travel,1):1;walking=progress<1;a.position.lerpVectors(from,to,progress);}}
   else a.position.copy(labs[i]);a.position.y=.02;
   const scale=.78;a.scale.setScalar(scale);const limbs=a.userData.limbs as THREE.Group[];limbs.forEach((limb,j)=>{limb.rotation.x=walking?Math.sin(elapsed*8+j*Math.PI)*.45:0;});
   const tag=agentLabels[i];tag.position.copy(a.position).add(new THREE.Vector3(0,.16*scale,0));tag.visible=active||(controls.target.distanceTo(hq)<18&&distance<7);tag.scale.set(.12,.0625,1);
  });
  updateLighting();windowLights.forEach(m=>{m.emissiveIntensity=nightAmount*2;});cityLife?.update(elapsed,controls.target,distance,nightAmount);oceanMaterial.uniforms.time.value=elapsed;ring.scale.setScalar(1+Math.sin(elapsed*2.5)*.055);
  container.dataset.agentScale='.78';container.dataset.agentHeightMeters='1.96';container.dataset.cameraX=camera.position.x.toFixed(4);container.dataset.cameraZ=camera.position.z.toFixed(4);container.dataset.targetX=controls.target.x.toFixed(4);container.dataset.targetZ=controls.target.z.toFixed(4);container.dataset.cameraTransition=String(!!(destinationPose||destination||destinationDistance!==null));container.dataset.cameraDistance=distance.toFixed(2);container.dataset.cameraHeight=camera.position.y.toFixed(3);container.dataset.streetView=String(streetView);facadeRoots.forEach(g=>{g.visible=distance<85&&!mapView;});const detailRadius=streetView?36:Math.max(12,Math.min(36,distance*.9));const detailKey=[Math.round(controls.target.x*4),Math.round(controls.target.z*4),Math.round(detailRadius),mapView,distance<85].join('|');if(detailKey!==lastDetailKey){lastDetailKey=detailKey;facadeTiles.forEach(tile=>{const detailed=distance<85&&!mapView&&Math.hypot(tile.x-controls.target.x,tile.z-controls.target.z)<detailRadius+5.7;tile.group.visible=detailed;tile.fallback.visible=!detailed&&!mapView;});}labels.forEach(s=>{s.visible=mapView||(distance>35&&s!==labels[4]);if(mapView)s.scale.set(distance*.14,distance*.0273,1);else s.scale.set(9,1.75,1);});
  let controlsChanged=false;if(streetView){if(!destinationPose){const heightDelta=.089-camera.position.y;camera.position.y=.089;controls.target.y+=heightDelta;}camera.lookAt(controls.target);}else{controlsChanged=controls.update();if(controls.target.y!==0){camera.position.y-=controls.target.y;controls.target.y=0;controlsChanged=true;}}updateShadows();if(!latest.current.paused&&!mapView&&now-lastShadowTime>160){renderer.shadowMap.needsUpdate=true;lastShadowTime=now;}const bearing=(streetView?Math.atan2(camera.position.x-controls.target.x,camera.position.z-controls.target.z):controls.getAzimuthalAngle())*180/Math.PI;mapHud?.style.setProperty('--map-bearing',bearing+'deg');mapHud?.classList.toggle('street-camera',streetView);if(scaleLabel&&!streetView){const a=new THREE.Vector3(),b=new THREE.Vector3();ray.setFromCamera(new THREE.Vector2(0,0),camera);const one=ray.ray.intersectPlane(groundPlane,a);ray.setFromCamera(new THREE.Vector2(.15,0),camera);const two=ray.ray.intersectPlane(groundPlane,b);if(one&&two){const metersPerPixel=a.distanceTo(b)*25/(container.clientWidth*.075),desired=metersPerPixel*90;const power=10**Math.floor(Math.log10(desired));const length=[1,2,5,10].map(n=>n*power).reduce((best,n)=>Math.abs(n-desired)<Math.abs(best-desired)?n:best,power);mapHud.style.setProperty('--map-scale-width',Math.min(130,Math.max(40,length/metersPerPixel))+'px');scaleLabel.textContent=length>=1000?(length/1000)+' km':Math.round(length)+' m';}}const renderKey=lightingMode+'|'+lastId+'|'+lastCategory+'|'+lastStage+'|'+architectureReady;if(renderRequested||!latest.current.paused||controlsChanged||(renderer.shadowMap.enabled&&renderer.shadowMap.needsUpdate)||renderKey!==lastRenderKey){renderer.render(scene,camera);lastRenderKey=renderKey;renderRequested=false;}
 };frame=requestAnimationFrame(render);

 return()=>{disposed=true;loadController.abort();window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('blur',clearKeys);cancelAnimationFrame(frame);observer.disconnect();controls.removeEventListener('start',cancelFlight);controls.dispose();renderer.domElement.removeEventListener('pointerdown',down);renderer.domElement.removeEventListener('pointerup',up);renderer.domElement.removeEventListener('pointermove',move);renderer.domElement.removeEventListener('pointercancel',cancelPointer);renderer.domElement.removeEventListener('contextmenu',contextMenu);renderer.domElement.removeEventListener('webglcontextlost',lostContext);const textures=new Set<THREE.Texture>(),materials=new Set<THREE.Material>(),geometries=new Set<THREE.BufferGeometry>();scene.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Sprite||o instanceof THREE.Line){if('geometry'in o)geometries.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material]){materials.add(m);const maps=m as THREE.Material&{map?:THREE.Texture;bumpMap?:THREE.Texture};for(const texture of [maps.map,maps.bumpMap,m.userData.originalMap])if(texture instanceof THREE.Texture)textures.add(texture);}}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());waterNormal.dispose();plaster.dispose();environment.dispose();renderer.dispose();container.replaceChildren();};
},[props.businesses]);return <div ref={host} className="city-canvas" role="img" aria-label="Ricostruzione tridimensionale di Bari con edifici, strade e costa da dati pubblici. Trascina per spostarti, tasto destro per ruotare e rotella per zoomare."/>;
}
