export type Business={id:string;name:string;category:string;lat:number|null;lon:number|null;address:string;website:string;source:string;sourceUrl:string;sourceDate:string;type:string;openingHours?:string;cin?:string;locationNote?:string};
export type Finding={title:string;state:'presente'|'non rilevato'|'da confermare';detail:string;url:string};
export type Report={business:Business;findings:Finding[];fetched:boolean;checkedAt:string;note:string;proposal:{title:string;description:string;kind?:string;trigger?:string};qa?:{title:string;passed:boolean}[]};
export function publicUrl(raw:string){try{const u=new URL(raw);if(!['https:','http:'].includes(u.protocol)||u.username||u.password||u.port||!u.hostname.includes('.')||/^[\d.]+$/.test(u.hostname)||u.hostname.includes(':')||/(^|\.)(localhost|local|internal|test|invalid|arpa)$/.test(u.hostname))return null;return u;}catch{return null;}}
async function boundedPage(raw:string){
 let u=publicUrl(raw);if(!u)throw new Error('Indirizzo non utilizzabile');
 for(let i=0;i<3;i++){
  const res=await fetch(u.href,{redirect:'manual',signal:AbortSignal.timeout(7000),headers:{'User-Agent':'BariAgentCity/1.0 public website review','Accept':'text/html'}});
  if(res.status>=300&&res.status<400){const next=publicUrl(new URL(res.headers.get('location')||'',u).href);if(!next)throw new Error('Reindirizzamento non utilizzabile');u=next;continue;}
  if(!res.ok||!/^text\/html(?:\s*;|\s*$)/i.test(res.headers.get('content-type')||''))throw new Error('Pagina non disponibile');
  const reader=res.body?.getReader();let html='',bytes=0,truncated=false;const decoder=new TextDecoder();
  if(reader)while(true){
   const p=await reader.read();if(p.done)break;
   const remaining=250000-bytes;const prefix=p.value.subarray(0,remaining);
   html+=decoder.decode(prefix,{stream:true});bytes+=prefix.length;
   if(p.value.length>remaining){truncated=true;await reader.cancel();break;}
  }
  html+=decoder.decode();return {html,url:u.href,truncated};
 }
 throw new Error('Troppi reindirizzamenti');
}
function pageEvidence(html:string){
 // Ignore code, hidden templates and comments; retain visible text and actual links/language attributes.
 const clean=html.replace(/<!--[\s\S]*?(?:-->|$)/g,' ').replace(/<(script|style|template)\b[^>]*>[\s\S]*?(?:<\/\1\s*>|$)/gi,' ');
 const attributes=[...clean.matchAll(/\b(href|lang|hreflang)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))/gi)].map(m=>`${m[1]}="${m[2]??m[3]??m[4]}"`).join(' ');
 return clean.replace(/<[^>]*(?:>|$)/g,' ')+' '+attributes;
}
export async function auditBusiness(b:Business):Promise<Report>{const findings:Finding[]=[{title:'Identità e attività',state:'presente',detail:`${b.type} · ${b.address||'Indirizzo non indicato nella fonte'}`,url:b.sourceUrl}];let html='',checkedUrl=b.website,note='Analisi preliminare delle fonti pubbliche. Il bisogno commerciale richiede conferma del titolare.';let fetched=false;
let truncated=false;
if(b.website){try{const p=await boundedPage(b.website);html=pageEvidence(p.html);checkedUrl=p.url;truncated=p.truncated;fetched=true;note+=' Controllata la pagina iniziale del sito; non le pagine interne o i processi aziendali.';if(truncated)note+=' Pagina letta solo in parte (limite di 250 KB): le funzioni non individuate restano da confermare.';}catch{note+=' Il sito non è stato raggiunto: nessuna conclusione sulle sue funzioni.';}}
findings.push({title:'Sito web nella fonte',state:b.website?'presente':'non rilevato',detail:b.website?'Indirizzo pubblicato nella fonte.':'Il campo non è compilato: non significa che l’azienda non abbia un sito.',url:b.website||b.sourceUrl});
const checks=[['Richiesta o prenotazione online',/\b(?:book(?:ing)?|prenot(?:a|are|azione|azioni)|octorate|reserv(?:e|ation|ations)|whatsapp)\b/i],['Informazioni in più lingue',/\bhreflang\s*=|\blang=["']en(?:[-"'])|\/en(?:\/|["'])|\b(?:english|deutsch)\b/i],['Orari o informazioni di contatto',/\b(?:orari(?:o)?|opening|contatt(?:i|o|a|aci)|contacts?)\b|(?:tel|mailto):/i]] as const;
for(const [title,re]of checks){const present=fetched&&re.test(html);findings.push({title,state:present?'presente':fetched&&!truncated?'non rilevato':'da confermare',detail:present?'Indizio trovato nel testo, nei link o nelle lingue dichiarate della pagina iniziale.':truncated?'La pagina è stata letta solo in parte: nessuna conclusione sull’assenza di questa funzione.':fetched?'Non individuato sulla pagina controllata; potrebbe essere altrove.':'Servono una pagina accessibile o informazioni del titolare.',url:checkedUrl||b.sourceUrl});}
const booking=findings[2],languages=findings[3],contact=findings[4];const kind=!fetched||truncated?'profile':booking.state==='non rilevato'?'request':languages.state==='non rilevato'?'bilingual':contact.state==='non rilevato'?'contacts':'feedback';const title=kind==='profile'?'Demo scheda dei servizi':kind==='bilingual'?'Demo di accoglienza bilingue':kind==='contacts'?'Demo informazioni e contatti':kind==='feedback'?'Demo di raccolta feedback':b.category==='Hotel'||b.category==='B&B e case vacanza'?'Demo di richiesta soggiorno':b.category==='Ristoranti'||b.category==='Bar e caffè'?'Demo di richiesta tavolo':'Demo di richiesta preventivo';const trigger=kind==='profile'?'Dati insufficienti per individuare una carenza: prima raccogliere le informazioni dal titolare.':kind==='request'?booking.title+' non rilevata nella pagina controllata.':kind==='bilingual'?languages.title+' non rilevate nella pagina controllata.':kind==='contacts'?contact.title+' non rilevati nella pagina controllata.':'Le funzioni cercate risultano presenti. Proposta esplorativa per raccogliere feedback dei clienti, senza una carenza accertata.';
return {business:b,findings,fetched,checkedAt:new Date().toISOString(),note,proposal:{title,kind,trigger,description:trigger+' È un’ipotesi da validare con l’azienda prima di sviluppare un prodotto commerciale.'}};}
export function demoHtml(r:Report){
 const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
 const messageLabel=r.proposal.kind==='feedback'?'Come possiamo migliorare il servizio?':r.proposal.kind==='profile'?'Quali servizi vuoi presentare?':'La tua richiesta';
 const bilingual=r.proposal.kind==='bilingual';
 const languageScript=bilingual?`let english=false;const translations={it:{prototype:'PROTOTIPO DIMOSTRATIVO · BARI AGENT CITY',title:'Demo di accoglienza bilingue',name:'Il tuo nome',message:'La tua richiesta',button:'Prova la richiesta',source:'Fonte pubblica dell’attività',initial:'Demo locale: i dati non vengono inviati o salvati. Nessuna affiliazione dichiarata con l’azienda.',completed:'Richiesta di prova completata. Questo esempio non invia dati all’azienda.'},en:{prototype:'DEMONSTRATION PROTOTYPE · BARI AGENT CITY',title:'Bilingual welcome demo',name:'Your name',message:'Your request',button:'Try the request',source:'Public source for this business',initial:'Local demo: information is neither sent nor saved. No affiliation with the business is claimed.',completed:'Test request completed. This example does not send information to the business.'}};function updateLanguage(){const text=translations[english?'en':'it'];document.documentElement.lang=english?'en':'it';document.getElementById('prototype').textContent=text.prototype;document.getElementById('demo-title').textContent=text.title;document.querySelector('label[for=name]').textContent=text.name;document.querySelector('label[for=message]').textContent=text.message;document.querySelector('#request button').textContent=text.button;document.getElementById('source').textContent=text.source;document.getElementById('result').textContent=submitted?text.completed:text.initial;document.getElementById('language').textContent=english?'Italiano':'English';document.title=text.title+' — '+document.querySelector('h1').textContent;}document.getElementById('language').addEventListener('click',()=>{english=!english;updateLanguage();});`:'';
 return `<!doctype html><html lang="it"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(r.proposal.title)} — ${escape(r.business.name)}</title><style>body{margin:0;background:#f4f2ea;color:#152e38;font:17px system-ui}main{box-sizing:border-box;width:calc(100% - 24px);max-width:640px;margin:8vh auto;padding:clamp(20px,5vw,36px);background:white;border-radius:24px}small{color:#55726d}h1{font-size:clamp(26px,7vw,38px);overflow-wrap:anywhere}label{display:block;margin:18px 0 8px}input,textarea,button{font:inherit;box-sizing:border-box;width:100%;padding:14px;border:1px solid #bbc7c4;border-radius:8px}button{background:#12665b;color:white;cursor:pointer;margin-top:20px}aside{padding:16px;background:#f4f2ea;border-radius:12px;margin-top:24px}</style><main><small id="prototype">PROTOTIPO DIMOSTRATIVO · BARI AGENT CITY</small><h1>${escape(r.business.name)}</h1>${bilingual?'<button type="button" id="language">English</button>':''}<p id="demo-title">${escape(r.proposal.title)}</p><form id="request"><label for="name">Il tuo nome</label><input id="name" required autocomplete="name"><label for="email">Email</label><input id="email" type="email" required autocomplete="email"><label for="message">${escape(messageLabel)}</label><textarea id="message" required rows="4"></textarea><button>Prova la richiesta</button></form><aside id="result" role="status">Demo locale: i dati non vengono inviati o salvati. Nessuna affiliazione dichiarata con l’azienda.</aside><p><a id="source" href="${escape(r.business.sourceUrl)}">Fonte pubblica dell’attività</a></p></main><script>let submitted=false;document.getElementById('request').addEventListener('submit',function(e){e.preventDefault();submitted=true;${bilingual?'updateLanguage();':"document.getElementById('result').textContent='Richiesta di prova completata. Questo esempio non invia dati all’azienda.';"}});${languageScript}</script></html>`;
}
