import type {Business,Prototype,PrototypeKind,Report} from './audit';

const escape=(text:string)=>text.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const stay=(b:Business)=>['Hotel','B&B e case vacanza'].includes(b.category);
const table=(b:Business)=>['Ristoranti','Bar e caffè'].includes(b.category);
const requestTitle=(b:Business)=>stay(b)?'Richiesta soggiorno':table(b)?'Richiesta tavolo':'Richiesta preventivo';

export function planPrototypes(report:Report):Prototype[]{
 const planned:Prototype[]=[];
 const add=(kind:PrototypeKind,title:string,reason:string)=>planned.push({id:kind,kind,title,reason,needsConfirmation:true,qa:[]});
 if(!report.business.website){
  add('website','Sito vetrina', 'Sito non indicato nella fonte pubblica. È un’ipotesi: il sito potrebbe già esistere.');
  return planned;
 }
 // An unreachable or partial page cannot justify diagnosing an absent service.
 if(!report.fetched)return planned;
 for(const finding of report.findings){
  if(finding.state!=='non rilevato')continue;
  const reason=finding.title+' non individuato nella pagina controllata. Potrebbe essere presente altrove.';
  if(finding.title==='Richiesta o prenotazione online')add('request',requestTitle(report.business),reason);
  if(finding.title==='Informazioni in più lingue')add('bilingual','Accoglienza italiano / inglese',reason);
  if(finding.title==='Orari o informazioni di contatto')add('contacts','Pagina informazioni e contatti',reason);
 }
 return planned;
}

export function prototypeHtml(report:Report,prototype:Prototype):string{
 const b=report.business,kind=prototype.kind,bilingual=kind==='bilingual';
 const lodging=stay(b),dining=table(b),request=kind==='request';
 const it={badge:'PROTOTIPO DIMOSTRATIVO · BARI AGENT CITY',nav:'Scopri l’attività',cta:'Prova una richiesta',category:b.category,hero:kind==='website'?'Uno spazio per presentare la tua attività.':kind==='bilingual'?'Le informazioni essenziali, in due lingue.':kind==='contacts'?'Le informazioni che aiutano a trovarti.':lodging?'Inizia la tua richiesta di soggiorno.':dining?'Un tavolo, con una semplice richiesta.':'Raccontaci il progetto che hai in mente.',intro:'Esempio da valutare con il titolare. I testi e le funzioni finali sono da concordare.',about:'L’attività in breve',aboutBody:'Questa sezione userà servizi, fotografie e descrizioni approvati dal titolare. Nessun servizio aggiuntivo è stato attribuito all’azienda.',address:'Indirizzo nella fonte',addressMissing:'Indirizzo da confermare con il titolare',hours:'Orari nella fonte',hoursMissing:'Orari da concordare con il titolare',contacts:'Contatti',contactsBody:'Email e telefono verificati saranno inseriti dopo conferma del titolare.',formTitle:request?requestTitle(b):'Prova il modulo di contatto',name:'Il tuo nome',email:'Email',message:'La tua richiesta',arrival:'Arrivo',departure:'Partenza',date:'Giorno',time:'Orario',guests:'Persone',button:'Prova la richiesta',initial:'Demo locale: i dati non vengono inviati o salvati. Non è una prenotazione.',completed:'Richiesta di prova completata. Questo esempio non invia dati all’azienda.',invalidDates:'La partenza deve essere successiva all’arrivo.',source:'Fonte pubblica dell’attività',footer:'Demo indipendente, senza affiliazione dichiarata con l’azienda. Il bisogno e le informazioni vanno confermati prima della pubblicazione.'};
 const en={badge:'DEMONSTRATION PROTOTYPE · BARI AGENT CITY',nav:'About the business',cta:'Try an enquiry',category:lodging?'Accommodation':dining?'Food and drink':'Local business',hero:'The essential information, in two languages.',intro:'An example for the owner to review. Final content and features need to be agreed.',about:'About the business',aboutBody:'This section will use services, photos and descriptions approved by the owner. No additional service has been attributed to the business.',address:'Address in the public source',addressMissing:'Address to be confirmed with the owner',hours:'Hours in the public source',hoursMissing:'Hours to be agreed with the owner',contacts:'Contact details',contactsBody:'Verified email and phone details will be added after the owner confirms them.',formTitle:'Try the contact form',name:'Your name',email:'Email',message:'Your enquiry',arrival:'Arrival',departure:'Departure',date:'Date',time:'Time',guests:'Guests',button:'Try the enquiry',initial:'Local demo: information is neither sent nor saved. This is not a reservation.',completed:'Test enquiry completed. This example does not send information to the business.',invalidDates:'Departure must be after arrival.',source:'Public source for this business',footer:'Independent demo. No affiliation with the business is claimed. The need and information must be confirmed before publication.'};
 type Key=keyof typeof it;
 const text=(key:Key)=>`<span data-text="${key}">${escape(it[key])}</span>`;
 const field=(id:string,label:Key,type='text',extra='')=>`<label for="${id}">${text(label)}</label><input id="${id}" name="${id}" type="${type}" required ${extra}>`;
 const dates=request&&lodging?`<div class="pair"><div>${field('arrival','arrival','date')}</div><div>${field('departure','departure','date')}</div></div>`:request&&dining?`<div class="pair"><div>${field('date','date','date')}</div><div>${field('time','time','time')}</div></div>`:'';
 const guests=request&&(lodging||dining)?field('guests','guests','number','min="1" max="20" value="2"'):'';
 const scriptTexts=JSON.stringify({it,en}).replace(/</g,'\\u003c');
 return `<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(prototype.title)} — ${escape(b.name)}</title><style>
 *{box-sizing:border-box}body{margin:0;font:16px system-ui,sans-serif;background:#f5f3ed;color:#16342e}a{color:inherit}button,input,textarea{font:inherit}button{cursor:pointer}a:focus-visible,button:focus-visible,input:focus-visible,textarea:focus-visible{outline:3px solid #df933f;outline-offset:4px}.badge{background:#173f35;color:#fff;text-align:center;padding:12px 18px;font-size:12px;letter-spacing:.07em}header,main,footer{max-width:1060px;margin:auto;padding:24px}header{display:flex;justify-content:space-between;align-items:center;gap:18px}.wordmark{font-weight:750;overflow-wrap:anywhere}nav{display:flex;align-items:center;gap:18px;font-size:14px}nav>a{white-space:nowrap}button,.cta{display:inline-block;padding:12px 18px;border:0;border-radius:8px;background:#174d3d;color:white;text-decoration:none;font-weight:650}.language{background:transparent;color:#174d3d;border:1px solid #97b8ac}.hero{display:grid;grid-template-columns:1.3fr 1fr;gap:40px;padding:40px 0 60px;align-items:center}.tag{font-size:13px;text-transform:uppercase;letter-spacing:.12em;color:#416b5c}h1{font-size:clamp(30px,5vw,56px);line-height:1.08;letter-spacing:-.04em;overflow-wrap:anywhere;margin:15px 0}h2{font-size:26px;letter-spacing:-.02em;margin:8px 0 18px}p{line-height:1.7;color:#49685d}.art{min-height:260px;border-radius:140px 140px 20px 20px;background:radial-gradient(circle at 70% 28%,#f0d79c 0 9%,transparent 10%),linear-gradient(165deg,#a5cbbd 0 60%,#295c50 61%);display:grid;place-items:end center;padding:35px}.art span{font-size:15px;letter-spacing:.16em;color:white}.layout{display:grid;grid-template-columns:1fr 1fr;gap:24px}.card{padding:28px;background:white;border:1px solid #dce6de;border-radius:16px;min-width:0}.info{padding:18px 0;border-bottom:1px solid #e3e9e3}.info strong{display:block;font-size:14px}.info p{margin:8px 0 0;overflow-wrap:anywhere}label{display:block;font-size:14px;font-weight:650;margin:15px 0 7px}input,textarea{width:100%;border:1px solid #a7beb2;border-radius:7px;padding:12px;background:#fcfdfb;min-width:0}.pair{display:grid;grid-template-columns:1fr 1fr;gap:14px}form button{width:100%;margin-top:20px}#result{background:#edf4ee;padding:15px;border-radius:8px;font-size:14px;line-height:1.6;margin-top:18px}footer{font-size:13px;padding-block:36px}footer a{display:inline-block;margin-bottom:8px}footer p{max-width:800px}@media(max-width:650px){header,main,footer{padding:20px}nav>a{display:none}.hero{grid-template-columns:1fr;gap:20px;padding:24px 0 35px}.art{min-height:160px;border-radius:80px 80px 15px 15px}.layout{grid-template-columns:1fr}.card{padding:20px}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto}}
 </style></head><body data-prototype="${kind}"><div class="badge">${text('badge')}</div><header><span class="wordmark">${escape(b.name)}</span><nav><a href="#about">${text('nav')}</a>${bilingual?'<button class="language" type="button" id="language">English</button>':''}</nav></header><main><section class="hero"><div><span class="tag">${text('category')} · Bari</span><h1>${text('hero')}</h1><p>${text('intro')}</p><a class="cta" href="#request">${text('cta')}</a></div><div class="art" aria-hidden="true"><span>BARI · PUGLIA</span></div></section><div class="layout"><section class="card" id="about"><h2>${text(kind==='contacts'?'contacts':'about')}</h2>${kind==='website'||bilingual?`<p>${text('aboutBody')}</p>`:''}<div class="info"><strong>${text('address')}</strong><p>${b.address?escape(b.address):text('addressMissing')}</p></div><div class="info"><strong>${text('hours')}</strong><p>${b.openingHours?escape(b.openingHours):text('hoursMissing')}</p></div><div class="info"><strong>${text('contacts')}</strong><p>${text('contactsBody')}</p></div></section><section class="card"><h2>${text('formTitle')}</h2><form id="request">${field('name','name','text','autocomplete="name"')}${field('email','email','email','autocomplete="email"')}${dates}${guests}<label for="message">${text('message')}</label><textarea id="message" name="message" required rows="4"></textarea><button type="submit">${text('button')}</button></form><div id="result" role="status">${text('initial')}</div></section></div></main><footer><a href="${escape(b.sourceUrl)}" target="_blank" rel="noreferrer">${text('source')}</a><p>${text('footer')}</p></footer><script>
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&window.parent!==window)window.parent.postMessage({type:'bari-prototype-close'},'*');});const translations=${scriptTexts};let language='it',submitted=false;const result=document.getElementById('result');function updateLanguage(){document.documentElement.lang=language;document.querySelectorAll('[data-text]').forEach(el=>el.textContent=translations[language][el.dataset.text]);result.textContent=translations[language][submitted?'completed':'initial'];const toggle=document.getElementById('language');if(toggle)toggle.textContent=language==='it'?'English':'Italiano';document.title=document.querySelector('h1').textContent+' — '+document.querySelector('.wordmark').textContent;}const toggle=document.getElementById('language');if(toggle)toggle.addEventListener('click',()=>{language=language==='it'?'en':'it';updateLanguage();});const arrival=document.getElementById('arrival'),departure=document.getElementById('departure');if(arrival){function dates(){departure.min=arrival.value;departure.setCustomValidity(departure.value&&departure.value<=arrival.value?translations[language].invalidDates:'');}arrival.addEventListener('input',dates);departure.addEventListener('input',dates);}document.getElementById('request').addEventListener('submit',function(e){e.preventDefault();submitted=true;result.textContent=translations[language].completed;});
 </script></body></html>`;
}

export function buildPrototypes(report:Report):Report{
 const prototypes=planPrototypes(report).map(prototype=>{
  const html=prototypeHtml(report,prototype);
  const qa=[{title:'Documento HTML completo',passed:html.startsWith('<!doctype html>')&&html.endsWith('</html>')},{title:'Modulo con etichette e validazione',passed:html.includes('for="email"')&&html.includes('type="email" required')},{title:'Richieste simulate senza invio',passed:html.includes('e.preventDefault()')&&!/fetch\(|XMLHttpRequest|https?:\/\/[^"\s]+\.(?:js|css)/.test(html)},{title:'Fonte e natura dimostrativa dichiarate',passed:html.includes('PROTOTIPO DIMOSTRATIVO')&&html.includes(escape(report.business.sourceUrl))}];
  return {...prototype,html,qa};
 });
 const first=prototypes[0];
 return {...report,prototypes,qa:prototypes.flatMap(p=>p.qa.map(q=>({...q,title:p.title+' · '+q.title}))),proposal:first?{kind:first.kind,title:first.title,trigger:first.reason,description:prototypes.map(p=>p.title+': '+p.reason).join('\n')}:{kind:'none',title:'Nessuna mancanza individuata con sufficiente evidenza',trigger:report.fetched?'Le funzioni controllate risultano presenti o restano da confermare.':'Il sito non è accessibile: servono informazioni dal titolare.',description:'Non è stato costruito un prototipo basato su una carenza non rilevata. '+report.note}};
}

// HTML artifacts remain stored server-side; lists contain only their descriptors.
export function publicReport(report:Report):Report{return {...report,prototypes:report.prototypes?.map(p=>({id:p.id,kind:p.kind,title:p.title,reason:p.reason,needsConfirmation:p.needsConfirmation,qa:p.qa}))};}
export function hasPrototype(report:Report){return report.prototypes===undefined||report.prototypes.length>0;}
